apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .Values.cluster_name }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .Values.cluster_name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: {{ .Values.vcluster_version }}
    values: |-
      sync:
        toHost:
          pods:
            runtimeClassName: kata-clh
        fromHost:
          nodes:
            enabled: true            # Enable node syncing for Azure Arc
      syncer:
        extraArgs:
          - "--fake-nodes=false"    # Disable fake nodes
          - "--fake-kubelets=false" # Disable fake kubelets
      controlPlane:
        statefulSet:
          resources:
            limits:
              cpu: 200m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
      policies:
        resourceQuota:
          enabled: true
          quota:
            requests.memory: 2Gi
            limits.cpu: 5000m
            limits.memory: 10Gi
            limits.ephemeral-storage: 300Gi
            requests.ephemeral-storage: 100Gi
            requests.storage: 10Gi
