apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .Values.cluster_name }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .Values.cluster_name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.namespace_name }}
spec:
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: {{ .Values.vcluster_version }}
    values: |-
      sync:
        toHost:
          pods:
            runtimeClassName: kata-clh
        fromHost:
          nodes:
            enabled: true            # Enable node syncing for Azure Arc
      syncer:
        extraArgs:
          - "--fake-nodes=false"    # Disable fake nodes
          - "--fake-kubelets=false" # Disable fake kubelets
      controlPlane:
        statefulSet:
          resources:
            limits:
              cpu: 200m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
      policies:
        resourceQuota:
          enabled: true
          quota:
            requests.cpu:     {{ add .Values.cluster_cpu 200 | add 3000 }}m      # Arc + control plane
            requests.memory:  {{ add .Values.cluster_ram 256 | add 2000 }}Mi    # Arc + control plane
            limits.cpu:       {{ add .Values.cluster_cpu 200 | add 5000 }}m     # Arc + control plane + buffer
            limits.memory:    {{ add .Values.cluster_ram 2048 | add 9000 }}Mi   # Arc + control plane + buffer
            limits.ephemeral-storage: 300Gi
            requests.ephemeral-storage: 100Gi
      
