name: Azure Arc Onboard (Windows Self-hosted)

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Name of the Kubernetes cluster (must match created vCluster)'
        required: true
      namespace_name:
        description: 'Namespace inside the cluster'
        required: true

jobs:
  onboard-cluster:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh  # PowerShell shell for Windows runner

    env:
      CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
      NAMESPACE_NAME: ${{ github.event.inputs.namespace_name }}
      RESOURCE_GROUP: AzureArcVClusterTest
      LOCATION: WestUS3
      KUBECONFIG: ${{ github.workspace }}\vcluster-kubeconfig.yaml

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate kubeconfig for vCluster
        run: |
          $kubeconfig = vcluster kubeconfig $env:CLUSTER_NAME -n $env:NAMESPACE_NAME
          $kubeconfig | Out-File -FilePath $env:KUBECONFIG -Encoding ascii
          Write-Host "KUBECONFIG written to $env:KUBECONFIG"

      - name: Confirm access to vCluster
        run: |
          kubectl config get-contexts
          kubectl get ns

      - name: Apply Azure Arc namespace and limitrange YAML
        run: |
          kubectl apply -f ./arc-ns/arc-ns.yaml

      - name: Create Resource Group in Azure (if not exists)
        run: |
          az group create `
            --name $env:RESOURCE_GROUP `
            --location $env:LOCATION `
            --output table

      - name: Connect Kubernetes Cluster to Azure Arc
        run: |
          az connectedk8s connect `
            --name $env:CLUSTER_NAME `
            --resource-group $env:RESOURCE_GROUP
